# -*- coding: utf-8 -*-
"""pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1raQHjAgBlqZG36-8bQqlt1zOinlQzMSe
"""

import numpy as np
import pandas as pd
pd.set_option('max_columns', None)

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import pickle

rf = pickle.load(open('diab_rf.pkl', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

def preprocess_outputs(df,scaler):
  df = df.copy()
  df = pd.DataFrame(scaler.transform(df), index = df.index, columns = df.columns)
  return df

def op_pred(filename):
  df = pd.read_csv(filename)
  df = preprocess_outputs(df,scaler)
  pred = rf.predict(df)
  res = []
  for row in range(df.shape[0]):
    if(pred[row]==0):
      res.append("No Trace of Diabetes Detected")
    else:
      res.append("Please consult a doctor for further process!")
  return res